name       : perl-sub-identify
version    : 0.14
release    : 1
source     :
    - http://search.cpan.org/CPAN/authors/id/R/RG/RGARCIA/Sub-Identify-0.14.tar.gz : 068d272086514dd1e842b6a40b1bedbafee63900e5b08890ef6700039defad6f
license    : Artistic-2.0
component  : programming.perl
summary    : |
    Sub::Identify allows you to retrieve the real name of code references.
description: |
    Sub::Identify allows you to retrieve the real name of code references.
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
